import React, { useMemo } from 'react';
import {
  Alert,
  ScrollView,
  Share,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';
import Card from '../../components/common/Card';
import ProgressBar from '../../components/common/ProgressBar';
import { useCircles } from '../../store/CircleContext';
import { Colors, FontSize, Radius, Spacing } from '../../theme';
import { Circle, Cycle, Member } from '../../types';
import { getCycleStats, getCircleStats } from '../../utils/calculations';
import { formatDate } from '../../utils/dateUtils';
import { circleStatusColor, formatCurrency, formatFrequency, formatStatus, statusColor } from '../../utils/formatters';
type Props = {
  navigation: any;
  route: any;
};

export default function CircleReportScreen({ navigation, route }: Props) {
  const { circleId } = route.params;
  const { getCircle } = useCircles();
  const circle = getCircle(circleId) as Circle | undefined;

  const stats = useMemo(() => circle ? getCircleStats(circle) : null, [circle]);

  if (!circle || !stats) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <Text style={{ fontSize: FontSize.lg, color: Colors.textSecondary }}>Circle not found.</Text>
        </View>
      </SafeAreaView>
    );
  }

  function getMember(id: string): Member | undefined {
    return circle!.members.find(m => m.id === id);
  }

  async function shareReport() {
    const lines: string[] = [
      `===== ${circle!.name} =====`,
      `Savings Circle — Planning Report`,
      '',
      `Status: ${circle!.status}`,
      `Payout per turn: ${formatCurrency(circle!.payoutAmount, circle!.currency)}`,
      `Contribution/person: ${formatCurrency(circle!.contributionAmount, circle!.currency)}`,
      `Frequency: ${formatFrequency(circle!.frequency)}`,
      `Members: ${circle!.numberOfMembers}`,
      `Start date: ${formatDate(circle!.startDate)}`,
      `Progress: ${stats!.completedCycles}/${stats!.totalCycles} cycles`,
      '',
      '— PAYOUT SCHEDULE —',
      ...circle!.cycles.map(cy => {
        const cs = getCycleStats(cy);
        const rec = getMember(cy.receivingMemberId);
        return `Cycle ${cy.cycleNumber} | ${formatDate(cy.dueDate)} | ${rec?.name ?? '—'} | ${formatCurrency(cy.totalPayout, circle!.currency)} | Paid: ${formatCurrency(cs.totalPaid, circle!.currency)}`;
      }),
      '',
      '— MEMBER SUMMARY —',
      ...circle!.members.map(m => {
        let paidCycles = 0;
        circle!.cycles.forEach(cy => {
          const p = cy.payments.find(p => p.memberId === m.id);
          if (p?.status === 'paid') { paidCycles++; }
        });
        return `${m.name}${m.isOrganizer ? ' (Organizer)' : ''}: ${paidCycles}/${circle!.cycles.length} cycles paid`;
      }),
      '',
      'Generated by Savings Circle — Planning & bookkeeping tool only.',
      'This app does not process payments or manage real money.',
    ];
    try {
      await Share.share({ message: lines.join('\n') });
    } catch {
      Alert.alert('Error', 'Could not share the report.');
    }
  }

  const sc = circleStatusColor(circle.status);

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}>
      <StatusBar backgroundColor={Colors.primary} barStyle="light-content" />
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Text style={styles.backIcon}>←</Text>
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle} numberOfLines={1}>{circle.name}</Text>
          <Text style={styles.headerSub}>Circle Report</Text>
        </View>
        <TouchableOpacity onPress={shareReport} style={styles.shareBtn}>
          <Text style={styles.shareIcon}>⬆️</Text>
        </TouchableOpacity>
      </View>

      <ScrollView
        style={{ flex: 1, backgroundColor: Colors.background }}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}>

        {/* Summary */}
        <Card variant="elevated" style={styles.summaryCard}>
          <View style={styles.summaryTop}>
            <View>
              <Text style={styles.bigAmount}>{formatCurrency(circle.payoutAmount, circle.currency)}</Text>
              <Text style={styles.bigAmtLabel}>per payout turn</Text>
            </View>
            <Badge label={circle.status} color={sc.text} bg={sc.bg} />
          </View>

          <View style={styles.grid}>
            <GridItem label="Contribution" value={formatCurrency(circle.contributionAmount, circle.currency)} />
            <GridItem label="Frequency" value={formatFrequency(circle.frequency)} />
            <GridItem label="Members" value={String(circle.numberOfMembers)} />
            <GridItem label="Start Date" value={formatDate(circle.startDate)} />
          </View>

          <ProgressBar
            percent={stats.progressPercent}
            label={`${stats.completedCycles} / ${stats.totalCycles} cycles completed`}
            color={Colors.primary}
          />

          <View style={styles.totalSection}>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total Collected</Text>
              <Text style={[styles.totalValue, { color: Colors.success }]}>{formatCurrency(stats.totalPaidOverall, circle.currency)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total Expected</Text>
              <Text style={styles.totalValue}>{formatCurrency(stats.totalExpectedOverall, circle.currency)}</Text>
            </View>
          </View>
        </Card>

        {/* Member summary */}
        <Text style={styles.sectionTitle}>MEMBER SUMMARY</Text>
        {circle.members.map(member => {
          let paidCycles = 0;
          let totalPaid = 0;
          circle.cycles.forEach(cy => {
            const p = cy.payments.find(pay => pay.memberId === member.id);
            if (p?.status === 'paid') { paidCycles++; totalPaid += cy.contributionPerMember; }
            else if (p?.status === 'partial') { totalPaid += p.paidAmount; }
          });
          const completion = circle.cycles.length > 0 ? (paidCycles / circle.cycles.length) * 100 : 0;

          return (
            <Card key={member.id} style={styles.memberCard}>
              <View style={styles.memberRow}>
                <View style={styles.avatar}>
                  <Text style={styles.avatarText}>{member.name.charAt(0).toUpperCase()}</Text>
                </View>
                <View style={{ flex: 1 }}>
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: Spacing.xs }}>
                    <Text style={styles.memberName}>{member.name}</Text>
                    {member.isOrganizer && (
                      <View style={styles.orgTag}><Text style={styles.orgTagText}>Organizer</Text></View>
                    )}
                  </View>
                  <Text style={styles.memberMeta}>Paid {paidCycles}/{circle.cycles.length} cycles · {formatCurrency(totalPaid, circle.currency)} collected</Text>
                  <ProgressBar percent={completion} showValue={false} height={4} color={Colors.primary} />
                </View>
              </View>
            </Card>
          );
        })}

        {/* Cycle-by-cycle */}
        <Text style={styles.sectionTitle}>CYCLE BREAKDOWN</Text>
        {circle.cycles.map(cycle => {
          const cs = getCycleStats(cycle);
          const receiver = getMember(cycle.receivingMemberId);
          const allDone = cs.paidCount + cs.excusedCount === cycle.payments.length;

          return (
            <Card key={cycle.id} style={styles.cycleCard}>
              <View style={styles.cycleHeader}>
                <View style={styles.cycleNumBadge}>
                  <Text style={styles.cycleNumText}>{cycle.cycleNumber}</Text>
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.cycleDate}>{formatDate(cycle.dueDate)}</Text>
                  <Text style={styles.cycleReceiver}>
                    {'→ '}<Text style={{ color: Colors.primary, fontWeight: '700' }}>{receiver?.name ?? '—'}</Text>
                  </Text>
                </View>
                <View style={{ alignItems: 'flex-end' }}>
                  <Text style={styles.cyclePayout}>{formatCurrency(cycle.totalPayout, circle.currency)}</Text>
                  <Badge
                    label={allDone ? 'Done' : `${cs.paidCount}/${cycle.payments.length}`}
                    color={allDone ? Colors.success : Colors.warning}
                    bg={allDone ? Colors.successBg : Colors.warningBg}
                    small
                  />
                </View>
              </View>

              {/* Individual payment statuses */}
              <View style={styles.paymentRows}>
                {cycle.payments.map(p => {
                  const mem = getMember(p.memberId);
                  const sc = statusColor(p.status);
                  return (
                    <View key={p.memberId} style={styles.paymentMiniRow}>
                      <Text style={styles.paymentMiniName} numberOfLines={1}>{mem?.name ?? '—'}</Text>
                      <View style={[styles.paymentMiniStatus, { backgroundColor: sc.bg }]}>
                        <Text style={[styles.paymentMiniStatusText, { color: sc.text }]}>{formatStatus(p.status)}</Text>
                      </View>
                    </View>
                  );
                })}
              </View>
            </Card>
          );
        })}

        <Button label="⬆️ Share Report" onPress={shareReport} style={{ marginTop: Spacing.md }} />

        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            Savings Circle is a planning and bookkeeping tool only. It does not process payments, hold funds, or guarantee payouts.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function GridItem({ label, value }: { label: string; value: string }) {
  return (
    <View style={giStyles.item}>
      <Text style={giStyles.label}>{label}</Text>
      <Text style={giStyles.value}>{value}</Text>
    </View>
  );
}

const giStyles = StyleSheet.create({
  item: { flex: 1, minWidth: '45%', marginBottom: Spacing.sm },
  label: { fontSize: FontSize.xs, color: Colors.textSecondary, fontWeight: '600' },
  value: { fontSize: FontSize.md, fontWeight: '700', color: Colors.text, marginTop: 2 },
});

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.primary },
  header: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  backBtn: { padding: Spacing.xs },
  backIcon: { fontSize: 22, color: '#fff', fontWeight: '700' },
  headerTitle: { fontSize: FontSize.xl, fontWeight: '800', color: '#fff' },
  headerSub: { fontSize: FontSize.sm, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
  shareBtn: { padding: Spacing.sm },
  shareIcon: { fontSize: 20 },
  content: { padding: Spacing.md, paddingBottom: Spacing.xxl },
  sectionTitle: {
    fontSize: FontSize.xs,
    fontWeight: '700',
    color: Colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: Spacing.sm,
    marginTop: Spacing.lg,
  },
  summaryCard: { marginBottom: Spacing.sm },
  summaryTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: Spacing.md },
  bigAmount: { fontSize: FontSize.xxxl, fontWeight: '800', color: Colors.primary },
  bigAmtLabel: { fontSize: FontSize.sm, color: Colors.textSecondary },
  grid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: Spacing.md },
  totalSection: { marginTop: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.borderLight, paddingTop: Spacing.md },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: Spacing.xs },
  totalLabel: { fontSize: FontSize.sm, color: Colors.textSecondary },
  totalValue: { fontSize: FontSize.md, fontWeight: '700', color: Colors.text },
  memberCard: { marginBottom: Spacing.sm },
  memberRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    backgroundColor: Colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: FontSize.lg, fontWeight: '700', color: Colors.primary },
  memberName: { fontSize: FontSize.md, fontWeight: '700', color: Colors.text },
  orgTag: { backgroundColor: Colors.accentBg, borderRadius: Radius.full, paddingHorizontal: 6, paddingVertical: 2 },
  orgTagText: { fontSize: FontSize.xs, color: Colors.accentDark, fontWeight: '700' },
  memberMeta: { fontSize: FontSize.sm, color: Colors.textSecondary, marginBottom: Spacing.xs },
  cycleCard: { marginBottom: Spacing.sm },
  cycleHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.sm },
  cycleNumBadge: {
    width: 32,
    height: 32,
    borderRadius: Radius.full,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cycleNumText: { fontSize: FontSize.sm, fontWeight: '800', color: '#fff' },
  cycleDate: { fontSize: FontSize.md, fontWeight: '700', color: Colors.text },
  cycleReceiver: { fontSize: FontSize.sm, color: Colors.textSecondary },
  cyclePayout: { fontSize: FontSize.md, fontWeight: '700', color: Colors.primary },
  paymentRows: {
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: Spacing.sm,
    gap: 4,
  },
  paymentMiniRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
  },
  paymentMiniName: { fontSize: FontSize.sm, color: Colors.text, flex: 1 },
  paymentMiniStatus: { borderRadius: Radius.full, paddingHorizontal: 8, paddingVertical: 2 },
  paymentMiniStatusText: { fontSize: FontSize.xs, fontWeight: '700' },
  disclaimer: {
    backgroundColor: Colors.borderLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.md,
  },
  disclaimerText: { fontSize: FontSize.sm, color: Colors.textSecondary, lineHeight: 20, textAlign: 'center' },
});
